### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by JArma19** [afshinrahimi/pigeo#4]
I'm trying to use pigeo in library mode, but .load_model() function cause always this error:
```
>>> pigeo.load_model()
04/25/2020 08:41:20 PM loading the saved model from pickle files in ./models/lrworld
04/25/2020 08:41:20 PM it might take about 2 minutes...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\arman\Desktop\pigeo\pigeo.py", line 467, in load_model
    params.coordinate_address = pickle.load(gzip.open(os.path.join(model_dir, 'coordinate_address.pkl.gz'), 'rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9a in position 0: ordinal not in range(128)
```
Could you please help me? Am I missing something?
Notice I followed the Quick Start guide.

**Comment by afshinrahimi** [comment]
What Python version are you using? This was written for Python 2 not Python 3.

**Comment by JArma19** [comment]
Ok, I forgot this requirement. Thanks
